# Generated by Django 4.0.3 on 2022-04-04 19:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_works_iswc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='contributors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, size=None),
        ),
    ]
